# Generated by Django 5.1.6 on 2025-03-21 08:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0005_article_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='slug',
        ),
    ]
