# Generated by Django 5.1.6 on 2025-03-21 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0009_alter_article_news_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='news_type',
            field=models.CharField(choices=[('', 'Select News Type'), ('diesel_vehicle', 'Diesel Vehicle'), ('electric_vehicle', 'Electric Vehicle'), ('banks_financial', 'Banks & Financial'), ('logistics_transport', 'Logistics and Transport')], default='', max_length=50),
        ),
    ]
