# Generated by Django 5.1.6 on 2025-03-21 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0010_alter_article_news_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='news_type',
            field=models.CharField(choices=[('Diesel Vehicle', 'Diesel Vehicle'), ('Electric Vehicle', 'Electric Vehicle'), ('Banks & Financial', 'Banks & Financial'), ('Logistics and Transport', 'Logistics and Transport')], default='diesel_vehicle', max_length=50),
        ),
    ]
