# Generated by Django 5.1.6 on 2025-03-22 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0013_pageviewcounter'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PageViewCounter',
        ),
    ]
