# Generated by Django 5.1.6 on 2025-03-22 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0015_page'),
    ]

    operations = [
        migrations.CreateModel(
            name='Website',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Wahid Business News', max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='Page',
        ),
    ]
