# Generated by Django 5.1.6 on 2025-04-02 18:19

import admin_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0017_mainmenu_submenu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='news_type',
            field=models.CharField(choices=admin_app.models.Article.get_article_types, max_length=50, verbose_name='Article Category'),
        ),
    ]
