# Generated by Django 5.1.6 on 2025-04-03 18:24

import admin_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0020_alter_article_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='thumbnail',
            field=models.ImageField(upload_to=admin_app.models.thumbnail_upload_to),
        ),
        migrations.AlterField(
            model_name='resourcesmodel',
            name='resource_file',
            field=models.FileField(upload_to='resources'),
        ),
    ]
