# Generated by Django 5.1.6 on 2025-03-17 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='thumbnail',
            field=models.ImageField(upload_to='thumbnails/'),
        ),
    ]
