# Generated by Django 5.1.6 on 2025-03-17 19:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_alter_article_thumbnail'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Article',
        ),
    ]
